- name: Check s4pred is present
  stat: path={{ app_location }}/s4pread
  register: s4pred_exist
  
- name: Check out s4pred from GIT
  when: s4pred_exist.stat.exists == False
  git:
    repo: https://github.com/psipred/s4pred.git
    dest: "{{ app_location }}/s4pred"
    clone: yes
    force: yes

- name: Install dependencies
  when: s4pred_exist.stat.exists == False
  become_user: "{{ django_worker_user }}"
  ansible.builtin.pip:
    name:
      - biopython
    chdir: "{{ django_worker_home }}"
    virtualenv: "{{ django_worker_home }}aa_env"
    virtualenv_command: /bin/virtualenv
    virtualenv_python: "{{ django_worker_home }}aa_env/bin/python"

- name: Download s4pred weights 
  when: s4pred_exist.stat.exists == False
  ansible.builtin.get_url:
    url: http://bioinfadmin.cs.ucl.ac.uk/downloads/s4pred/weights.tar.gz
    dest: "{{ app_location }}/s4pred/weights.tar.gz"
  
- name: Extract s4pred weights
  when: s4pred_exist.stat.exists == False
  ansible.builtin.unarchive:
    src: "{{ app_location }}/s4pred/weights.tar.gz"
    dest: "{{ app_location }}/s4pred/"
    remote_src: yes
    
- name: remove weights tar.gz
  when: s4pred_exist.stat.exists == False
  ansible.builtin.file:
    state: absent
    path: "{{ app_location }}/s4pred/weights.tar.gz"
