- name: Check gsrcl is present
  stat: path={{ app_location }}/gsrcl
  register: gsrcl_exist
  
- name: Check out gsrcl from GIT
  when: gsrcl_exist.stat.exists == False
  git:
    repo: https://github.com/psipred/GsRCL.git
    dest: "{{ app_location }}/gsrcl"
    clone: yes
    force: yes

- name: Install requirements
  when: gsrcl_exist.stat.exists == False
  become_user: "{{ django_worker_user }}"
  pip:
    state: latest
    chdir: "{{ django_worker_home }}"
    virtualenv: "{{ django_worker_home }}aa_env"
    virtualenv_command: /bin/virtualenv
    virtualenv_python: "{{ django_worker_home }}aa_env/bin/python"
    requirements: "{{ app_location}}/gsrcl/requirements.txt"

- name: remove symlink
  ansible.builtin.file:
    state: absent
    path: "{{ app_location }}/gsrcl/data"

- name: make weights dir
  ansible.builtin.file:
    state: directory
    path: "{{ app_location }}/gsrcl_weights/"

- name: symlink data
  file:
    src: "{{ app_location }}/gsrcl_weights/"
    dest: "{{ app_location }}/gsrcl/data"
    state: link
    mode: "ug+rw"

- name: Download gsrcl weights
  when: gsrcl_exist.stat.exists == False
  ansible.builtin.get_url:
    url: https://zenodo.org/api/records/10050548/files-archive
    dest: "{{ app_location }}/gsrcl_classifiers.zip"
  
- name: Extract gsrcl weights
  when: gsrcl_exist.stat.exists == False
  ansible.builtin.unarchive:
    src: "{{ app_location }}/gsrcl_classifiers.zip"
    dest: "{{ app_location }}/gsrcl_weights/"
    remote_src: yes
    
- name: remove weights
  when: gsrcl_exist.stat.exists == False
  ansible.builtin.file:
    state: absent
    path: "{{ app_location }}/gsrcl_classifiers.zip"

# rename all the files, so repetitive

- name: unzip Adam
  ansible.builtin.command:
    cmd: unzip {{ app_location }}/gsrcl_weights/Adam.zip

- name: remove weights
  ansible.builtin.file:
    state: absent
    path: "{{ app_location }}/Adam.zip"

###

- name: unzip Baron Human
  ansible.builtin.command:
    chdir: "{{ app_location }}/gsrcl_weights/"
    cmd: unzip {{ app_location }}/gsrcl_weights/Baron\ Human.zip
    
- name: mv dir Baron Human
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/Baron\ Human {{ app_location }}/gsrcl_weights/BaronHuman
    
- name: mv Baron Human reference
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/BaronHuman/Baron\ Human-reference-genes.csv {{ app_location }}/gsrcl_weights/BaronHuman/BaronHuman-reference-genes.csv

- name: remove weights
  ansible.builtin.file:
    state: absent
    path: "{{ app_location }}/Baron Human.zip"

##

- name: unzip Baron Mouse
  ansible.builtin.command:
    chdir: "{{ app_location }}/gsrcl_weights/"
    cmd: unzip {{ app_location }}/gsrcl_weights/Baron\ Mouse.zip
    
- name: mv dir Baron Mouse
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/Baron\ Mouse {{ app_location }}/gsrcl_weights/BaronMouse
    
- name: mv Baron Mouse reference
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/BaronMouse/Baron\ Mouse-reference-genes.csv {{ app_location }}/gsrcl_weights/BaronMouse/BaronMouse-reference-genes.csv

- name: remove weights
  ansible.builtin.file:
    state: absent
    path: "{{ app_location }}/Baron Mouse.zip"

###

- name: unzip Klien
  ansible.builtin.command:
    chdir: "{{ app_location }}/gsrcl_weights/"
    cmd: unzip {{ app_location }}/gsrcl_weights/Klien.zip

- name: remove weights
  ansible.builtin.file:
    state: absent
    path: "{{ app_location }}/Klien.zip"

###

- name: unzip Muraro
  ansible.builtin.command:
    chdir: "{{ app_location }}/gsrcl_weights/"
    cmd: unzip {{ app_location }}/gsrcl_weights/Muraro.zip

- name: remove weights
  ansible.builtin.file:
    state: absent
    path: "{{ app_location }}/Muraro.zip"

###

- name: unzip PbmcBench_10Xv2.zip
  ansible.builtin.command:
    chdir: "{{ app_location }}/gsrcl_weights/"
    cmd: unzip {{ app_location }}/gsrcl_weights/PbmcBench_10Xv2.zip
    
- name: mv dir PbmcBench_10Xv2
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/PbmcBench_10Xv2 {{ app_location }}/gsrcl_weights/PbmcBench10Xv2
    
- name: mv PbmcBench_10Xv2 reference
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/PbmcBench10Xv2/PbmcBench_10Xv2-reference-genes.csv {{ app_location }}/gsrcl_weights/PbmcBench10Xv2/PbmcBench10Xv2-reference-genes.csv

- name: remove weights
  ansible.builtin.file:
    state: absent
    path: "{{ app_location }}/PbmcBench_10Xv2.zip"

###

- name: unzip PbmcBench_10Xv3.zip
  ansible.builtin.command:
    chdir: "{{ app_location }}/gsrcl_weights/"
    cmd: unzip {{ app_location }}/gsrcl_weights/PbmcBench_10Xv3.zip
    
- name: mv dir PbmcBench_10Xv3
  ansible.builtin.command:
    chdir: "{{ app_location }}/gsrcl_weights/"
    cmd: mv {{ app_location }}/gsrcl_weights/PbmcBench_10Xv3 {{ app_location }}/gsrcl_weights/PbmcBench10Xv3
    
- name: mv PbmcBench_10Xv3 reference
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/PbmcBench10Xv3/PbmcBench_10Xv3-reference-genes.csv {{ app_location }}/gsrcl_weights/PbmcBench10Xv3/PbmcBench10Xv3-reference-genes.csv

- name: remove weights
  ansible.builtin.file:
    state: absent
    path: "{{ app_location }}/PbmcBench_10Xv3.zip"

###

- name: unzip PbmcBench_Drop-Seq.zip
  ansible.builtin.command:
    chdir: "{{ app_location }}/gsrcl_weights/"
    cmd: unzip {{ app_location }}/gsrcl_weights/PbmcBench_Drop-Seq.zip
    
- name: mv dir PbmcBench_Drop-Seq
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/PbmcBench_Drop-Seq {{ app_location }}/gsrcl_weights/PbmcBenchDropSeq
    
- name: mv PbmcBench_Drop-Seq reference
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/PbmcBenchDropSeq/PbmcBench_Drop-Seq-reference-genes.csv {{ app_location }}/gsrcl_weights/PbmcBenchDropSeq/PbmcBenchDropSeq-reference-genes.csv

- name: remove weights
  ansible.builtin.file:
    state: absent
    path: "{{ app_location }}/PbmcBench_Drop-Seq.zip"

###

- name: unzip PbmcBench_inDrop.zip
  ansible.builtin.command:
    chdir: "{{ app_location }}/gsrcl_weights/"
    cmd: unzip {{ app_location }}/gsrcl_weights/PbmcBench_inDrop.zip
    
- name: mv dir PbmcBench_inDrop
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/PbmcBench_inDrop {{ app_location }}/gsrcl_weights/PbmcBenchinDrop
    
- name: mv PbmcBench_inDrop reference
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/PbmcBenchinDrop/PbmcBench_inDrop-reference-genes.csv {{ app_location }}/gsrcl_weights/PbmcBenchinDrop/PbmcBenchinDrop-reference-genes.csv

- name: remove weights
  ansible.builtin.file:
    state: absent
    path: "{{ app_location }}/PbmcBench_inDrop.zip"

###

- name: unzip PbmcBench_Seq-Well.zip
  ansible.builtin.command:
    chdir: "{{ app_location }}/gsrcl_weights/"
    cmd: unzip {{ app_location }}/gsrcl_weights/PbmcBench_Seq-Well.zip
    
- name: mv dir PbmcBench_Seq-Well
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/PbmcBench_Seq-Well {{ app_location }}/gsrcl_weights/PbmcBenchSeqWell
    
- name: mv PbmcBench_Seq-Well reference
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/PbmcBenchSeqWell/PbmcBench_Seq-Well-reference-genes.csv {{ app_location }}/gsrcl_weights/PbmcBenchSeqWell/PbmcBenchSeqWell-reference-genes.csv

- name: remove weights
  ansible.builtin.file:
    state: absent
    path: "{{ app_location }}/PbmcBench_Seq-Well.zip"

###

- name: unzip Quake_10x_Bladder.zip
  ansible.builtin.command:
    chdir: "{{ app_location }}/gsrcl_weights/"
    cmd: unzip {{ app_location }}/gsrcl_weights/Quake_10x_Bladder.zip
    
- name: mv dir Quake_10x_Bladder
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/Quake_10x_Bladder {{ app_location }}/gsrcl_weights/Quake10xBladder
    
- name: mv Quake_10x_Bladder reference
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/Quake10xBladder/Quake_10x_Bladder-reference-genes.csv {{ app_location }}/gsrcl_weights/Quake10xBladder/Quake10xBladder-reference-genes.csv

- name: remove weights
  ansible.builtin.file:
    state: absent
    path: "{{ app_location }}/Quake_10x_Bladder.zip"


###

- name: unzip Quake_10x_Limb_Muscle.zip
  ansible.builtin.command:
    chdir: "{{ app_location }}/gsrcl_weights/"
    cmd: unzip {{ app_location }}/gsrcl_weights/Quake_10x_Limb_Muscle.zip
    
- name: mv dir Quake_10x_Limb_Muscle
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/Quake_10x_Limb_Muscle {{ app_location }}/gsrcl_weights/Quake10xMuscle
    
- name: mv Quake_10x_Limb_Muscle reference
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/Quake10xMuscle/Quake_10x_Limb_Muscle-reference-genes.csv {{ app_location }}/gsrcl_weights/Quake10xMuscle/Quake10xLimbMuscle-reference-genes.csv

- name: remove weights
  ansible.builtin.file:
    state: absent
    path: "{{ app_location }}/Quake_10x_Limb_Muscle.zip"

###

- name: unzip Quake_Smart-seq2_Diaphragm.zip
  ansible.builtin.command:
    chdir: "{{ app_location }}/gsrcl_weights/"
    cmd: unzip {{ app_location }}/gsrcl_weights/Quake_Smart-seq2_Diaphragm.zip
    
- name: mv dir Quake_Smart-seq2_Diaphragm
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/Quake_Smart-seq2_Diaphragm {{ app_location }}/gsrcl_weights/QuakeSmartseq2Diaphragm
    
- name: mv Quake_Smart-seq2_Diaphragm reference
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/QuakeSmartseq2Diaphragm/Quake_Smart-seq2_Diaphragm-reference-genes.csv {{ app_location }}/gsrcl_weights/QuakeSmartseq2Diaphragm/QuakeSmartseq2Diaphragm-reference-genes.csv

- name: remove weights
  ansible.builtin.file:
    state: absent
    path: "{{ app_location }}/Quake_Smart-seq2_Diaphragm.zip"

###

- name: unzip Quake_Smart-seq2_Limb_Muscle.zip
  ansible.builtin.command:
    chdir: "{{ app_location }}/gsrcl_weights/"
    cmd: unzip {{ app_location }}/gsrcl_weights/Quake_Smart-seq2_Limb_Muscle.zip
    
- name: mv dir Quake_Smart-seq2_Limb_Muscle
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/Quake_Smart-seq2_Limb_Muscle {{ app_location }}/gsrcl_weights/QuakeSmartseq2LimbMuscle
    
- name: mv Quake_Smart-seq2_Limb_Muscle reference
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/QuakeSmartseq2LimbMuscle/Quake_Smart-seq2_Limb_Muscle-reference-genes.csv {{ app_location }}/gsrcl_weights/QuakeSmartseq2LimbMuscle/QuakeSmartseq2LimbMuscle-reference-genes.csv

- name: remove weights
  ansible.builtin.file:
    state: absent
    path: "{{ app_location }}/Quake_Smart-seq2_Limb_Muscle.zip"

###

- name: unzip Quake_Smart-seq2_Lung.zip
  ansible.builtin.command:
    chdir: "{{ app_location }}/gsrcl_weights/"
    cmd: unzip {{ app_location }}/gsrcl_weights/Quake_Smart-seq2_Lung.zip
    
- name: mv dir Quake_Smart-seq2_Lung
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/Quake_Smart-seq2_Lung {{ app_location }}/gsrcl_weights/QuakeSmartseq2Lung
    
- name: mv Quake_Smart-seq2_Lung reference
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/QuakeSmartseq2Lung/Quake_Smart-seq2_Lung-reference-genes.csv {{ app_location }}/gsrcl_weights/QuakeSmartseq2Lung/QuakeSmartseq2Lung-reference-genes.csv

- name: remove weights
  ansible.builtin.file:
    state: absent
    path: "{{ app_location }}/Quake_Smart-seq2_Lung.zip"

###

- name: unzip Quake_Smart-seq2_Trachea.zip
  ansible.builtin.command:
    chdir: "{{ app_location }}/gsrcl_weights/"
    cmd: unzip {{ app_location }}/gsrcl_weights/Quake_Smart-seq2_Trachea.zip
    
- name: mv dir Quake_Smart-seq2_Trachea
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/Quake_Smart-seq2_Trachea {{ app_location }}/gsrcl_weights/QuakeSmartseq2Trachea
    
- name: mv Quake_Smart-seq2_Trachea reference
  ansible.builtin.command:
    cmd: mv {{ app_location }}/gsrcl_weights/QuakeSmartseq2Trachea/Quake_Smart-seq2_Trachea-reference-genes.csv {{ app_location }}/gsrcl_weights/QuakeSmartseq2Trachea/QuakeSmartseq2Trachea-reference-genes.csv

- name: remove weights
  ansible.builtin.file:
    state: absent
    path: "{{ app_location }}/Quake_Smart-seq2_Trachea.zip"

###

- name: unzip Romanov
  ansible.builtin.command:
    chdir: "{{ app_location }}/gsrcl_weights/"
    cmd: unzip {{ app_location }}/gsrcl_weights/Romanov.zip

- name: remove weights
  ansible.builtin.file:
    state: absent
    path: "{{ app_location }}/Romanov.zip"

###

- name: unzip Segerstolpe
  ansible.builtin.command:
    chdir: "{{ app_location }}/gsrcl_weights/"
    cmd: unzip {{ app_location }}/gsrcl_weights/Segerstolpe.zip

- name: remove weights
  ansible.builtin.file:
    state: absent
    path: "{{ app_location }}/Segerstolpe.zip"

###

- name: unzip Xin
  ansible.builtin.command:
    chdir: "{{ app_location }}/gsrcl_weights/"
    cmd: unzip {{ app_location }}/gsrcl_weights/Xin.zip

- name: remove weights
  ansible.builtin.file:
    state: absent
    path: "{{ app_location }}/Xin.zip"
