  - name : Check Out update scripts from GIT
    become_user: "{{ blast_worker_user }}"
    git:
      repo: https://github.com/psipred/server_update.git
      dest: "{{ blast_worker_home }}/server_update"
      clone: yes
      force: yes

  - name: make tmp dir
    shell: mkdir {{ app_location }}/update_tmp; chown blast_worker {{ app_location }}/update_tmp

  - name: add blast db updates
    become_user: "{{ blast_worker_user }}"
    cron:
      name: "Clean update seqdb"
      minute: "0"
      hour: "2"
      day: "1"
      job: "/usr/bin/sh {{ blast_worker_home }}/server_update/update_blast_sequence_databases.sh > /dev/null 2>&1"

  # - name: add pdb data update
  #   become_user: "{{ blast_worker_user }}"
  #   cron:
  #     name: "Clean update seqdb"
  #     minute: "0"
  #     hour: "4"
  #     day: "1"
  #     job: "/usr/bin/sh {{ blast_worker_home }}/server_update/update_data_sequence_databases.sh > /dev/null 2>&1"

