- name: Install dependencies
  become_user: "{{ django_worker_user }}"
  ansible.builtin.pip:
    name:
      - dmpfold
    chdir: "{{ django_worker_home }}"
    virtualenv: "{{ django_worker_home }}aa_env"
    virtualenv_command: /bin/virtualenv
    virtualenv_python: "{{ django_worker_home }}aa_env/bin/python"

# https://github.com/psipred/DMPfold2/pull/8
# Here we monkey patch dmpfold2, as we can't run too many different pytorch versions on the server
- name: swap symeigh with linalg.eigh
  ansible.builtin.lineinfile:
    path: /home/django_worker/aa_env/lib/python3.9/site-packages/dmpfold/network.py
    regexp: 'w, v = torch.symeig'
    line: 'w, v = torch.linalg.eigh(M.float())''