---
#
# INSTALLING TO /webdata as we are out of room in /opt ffs
#
#
  - name: "install gnuplot"
    dnf:
      pkg: gnuplot
      state: latest
    become_user: root
    become_method: sudo

  - name: Check if dompred is present
    stat: path={{ app_location }}/dompred/parseDS.pl
    register: dompred_exist

  - name : Check Out dompred from git
    when: dompred_exist.stat.exists == False
    git:
      repo: https://github.com/psipred/dompred.git
      dest: "{{ app_location }}/dompred"
      clone: yes
      force: yes

  - name: Download data files
    when: dompred_exist.stat.exists == False
    get_url:
      url: http://bioinfadmin.cs.ucl.ac.uk/downloads/dompred_data/dompred_data.tar.gz
      dest: "{{ app_location }}/dompred/"
      timeout: 120
    register: get_url_result

  - name: untar dompred data
    when: dompred_exist.stat.exists == False
    unarchive:
      src: "{{ app_location }}/dompred/dompred_data.tar.gz"
      dest: "{{ app_location }}/dompred/"
      remote_src: yes

  - name: remove tar.gz
    when: dompred_exist.stat.exists == False
    ansible.builtin.file:
      state: absent
      path: "{{ app_location }}/dompred/dompred_data.tar.gz"

  - name: compile DomSSEA
    when: dompred_exist.stat.exists == False
    shell: cd {{ app_location }}/dompred/src; javac DomSSEA.java
