---

  - name: Get the current firewalld rules
    shell: firewall-cmd --list-all
    register: firewalldrules
    check_mode: no
    become_user: root
    become_method: sudo

  - name: Add http firewalld rules
    command: firewall-cmd --zone=public --add-service=http --permanent
    become_user: root
    become_method: sudo
    when: firewalldrules.stdout.find("http") == -1

  - name: Enable firewalld port forwarding
    command: firewall-cmd --zone=public --add-masquerade --permanent
    become_user: root
    become_method: sudo
    when: firewalldrules.stdout.find("http") == -1

  - name: Portforward 80 to 8000
    command: firewall-cmd --zone=public --add-forward-port=port=80:proto=tcp:toport=8000 --permanent
    become_user: root
    become_method: sudo
    when: firewalldrules.stdout.find("http") == -1

  - name: Portforward 443 to 4433
    command: firewall-cmd --zone=public --add-forward-port=port=443:proto=tcp:toport=4433 --permanent
    become_user: root
    become_method: sudo
    when: firewalldrules.stdout.find("http") == -1

  - name: Reload firewalld
    command: firewall-cmd --reload
    become_user: root
    become_method: sudo

  - name: Install httpd
    dnf:
      pkg: httpd, httpd-devel
      state: latest
    become_user: root
    become_method: sudo

  - name: Install VirtualEnv
    dnf:
      pkg: python-virtualenv
      state: latest
    become_user: root
    become_method: sudo

  - name: Install pip4
    dnf:
      pkg: python3-pip
      state: latest
    become_user: root
    become_method: sudo

  - name: Install virtualenvwrapper
    ansible.builtin.pip:
      name: virtualenvwrapper
    become_user: root
    become_method: sudo

  - name: Install blas/lapack
    dnf:
      pkg: blas, lapack, blas-devel, lapack-devel
      state: latest
    become_user: root
    become_method: sudo

  - name: Install R
    dnf:
      pkg: R-core, R-core-devel
      state: latest
    become_user: root
    become_method: sudo

