  - name: Get the current firewalld rules
    shell: firewall-cmd --list-all
    register: firewalldrules
    check_mode: no
    become_user: root
    become_method: sudo

  - name: Add http firewalld rules
    command: firewall-cmd --zone=public --add-port=80/tcp --permanent
    become_user: root
    become_method: sudo
    when: firewalldrules.stdout.find("http") == -1

  - name: Reload firewalld
    command: firewall-cmd --reload
    become_user: root
    become_method: sudo

  - name: Install npm
    dnf:
      pkg: npm
      state: latest
    become_user: root
    become_method: sudo

  - name : Check Out PSIPRED React website from git
    become_user: root
    git:
      repo: https://github.com/psipred/psipred_react.git
      dest: /var/www/psipred_react
      clone: yes
      force: yes

  - name: Install npm packages
    become_user: root
    shell: cd /var/www/psipred_react; npm install

  # https://bobbyhadz.com/blog/create-react-app-set-public-url
  - name: build website
    become_user: root
    shell: cd /var/www/psipred_react; PUBLIC_URL={{ public_url }} npm run build

  - name: Copy httpd conf
    become_user: root
    copy:
      src: files/psipred_react_httpd.conf
      dest: /etc/httpd/conf/httpd.conf
      owner: root

  - name: index.html in to place
    become_user: root
    copy:
      src: /var/www/psipred_react/public/index_{{ my_env }}.html
      dest: /var/www/psipred_react/public/index.html
      owner: root
      remote_src: yes
      
  - name: Enable service httpd
    become_user: root
    ansible.builtin.systemd:
      name: httpd
      enabled: true
  
  - name: Make sure httpd is running
    become_user: root
    ansible.builtin.systemd:
      state: restarted
      name: httpd
