  
  - name: clone DMP
    git:
      repo: https://github.com/psipred/DeepMetaPSICOV.git
      dest: "{{ app_location }}/DeepMetaPSICOV"
      clone: yes
      force: yes

  - name: get Rcpp
    shell: "chdir={{ app_location }}/ wget https://cran.r-project.org/src/contrib/Rcpp_1.0.12.tar.gz"

  - name: install Rcpp
    shell: "chdir={{ app_location }}/ R CMD INSTALL Rcpp_1.0.12.tar.gz"
    become_user: root

  - name: get bio3d
    shell:  "chdir={{ app_location }}/ wget https://cran.r-project.org/src/contrib/bio3d_2.4-4.tar.gz"

  - name: install bio3d
    shell: "chdir={{ app_location }}/ R CMD INSTALL bio3d_2.4-4.tar.gz"
    become_user: root

  - name: get colorRamps
    shell:  "chdir={{ app_location }}/ wget https://cran.r-project.org/src/contrib/colorRamps_2.3.4.tar.gz"

  - name: install colorRamps
    shell: "chdir={{ app_location }}/ R CMD INSTALL colorRamps_2.3.4.tar.gz"
    become_user: root

  - name: remove rcpp dom tar.gz
    ansible.builtin.file:
      state: absent
      path: "{{ app_location }}/Rcpp_1.0.12.tar.gz"

  - name: remove bio3d dom tar.gz
    ansible.builtin.file:
      state: absent
      path: "{{ app_location }}/bio3d_2.4-4.tar.gz"

  - name: remove colorRamps tar.gz
    ansible.builtin.file:
      state: absent
      path: "{{ app_location }}/colorRamps_2.3.4.tar.gz"
